### ISSUE TITLE
Unable to load metadata

### ISSUE THREAD

**Issue by rakzcs** [openmaptiles/openmaptiles#1001]
hi

Germany, Australia and maybe some other countries have an error of unable to load metadata.

```
ID 'dacs' was not found in Geofabrik.
Unable to load metadata for dacs from http://download.openstreetmap.fr/extracts/dacs-latest.osm.pbf: Status=404 for HEAD request
Unable to load md5 hash for dacs from http://download.openstreetmap.fr/extracts/dacs-latest.osm.pbf.md5: Received status=404
Unable to auto-detect the source for 'dacs'
Makefile:283: recipe for target 'download' failed
```

**Comment by eva-j** [comment]
Hi @rakzcs,
I am not sure if I understand you correctly, but I guess you maybe wanted to download "dach" area. You can list all possible geofabrik pbf files using `make list-geofabrik`.

**Comment by rakzcs** [comment]
Yeah, davs is a example that also did not work with the same error. If dacs or germany is not available then the guides need to be updated.

**Comment by eva-j** [comment]
Can you share a link to the guides you mentioned?

**Comment by rakzcs** [comment]
https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md

**Comment by eva-j** [comment]
There is nothing about dacs. `./quickstart.sh germany` works.

**Comment by rakzcs** [comment]
still, germany is not working

```
====> : Start importing OpenStreetMap data: germany -> imposm3[./build/mapping.yaml] -> PostgreSQL
      : Imposm3 documentation: https://imposm.org/docs/imposm3/latest/index.html 
      :   Thank you Omniscale! 
      :   Source code: https://github.com/openmaptiles/openmaptiles-tools/tree/master/docker/import-osm 
      : The OpenstreetMap data license: https://www.openstreetmap.org/copyright (ODBL) 
      : Thank you OpenStreetMap Contributors ! 
Starting postgres docker compose target using default image (no recreate if exists)
Starting openmaptiles_postgres_1 ... done
docker-compose  run --rm --user=0:0 openmaptiles-tools sh -c 'pgwait && import-osm data/germany.osm.pbf'
Importing provided file data/germany.osm.pbf
Importing data/germany.osm.pbf into postgres:5432/openmaptiles using Imposm in NORMAL mode...
2020/09/28 11:14:07 lowlevel.go:81: unmarshaling error: proto: osmpbf.DenseNodes: illegal tag 0 (wire type 1) 0/s (0) R:      0/s      0/s (0)
panic: unmarshaling error: proto: osmpbf.DenseNodes: illegal tag 0 (wire type 1)

goroutine 76 [running]:
log.Panic(0xc000307de8, 0x2, 0x2)
        /usr/local/go/src/log/log.go:338 +0xac
github.com/omniscale/imposm3/parser/pbf.readPrimitiveBlock(0x7ffeb16b0aa7, 0x14, 0x38e9026, 0x19fd0, 0x1be)
        /go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:81 +0x187
github.com/omniscale/imposm3/parser/pbf.(*Parser).parseBlock(0xc0000ba320, 0x7ffeb16b0aa7, 0x14, 0x38e9026, 0x19fd0)
        /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:89 +0x68
github.com/omniscale/imposm3/parser/pbf.(*Parser).Parse.func1(0xc00008ae40, 0xc0000ba320)
        /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:56 +0x89
created by github.com/omniscale/imposm3/parser/pbf.(*Parser).Parse
        /go/src/github.com/omniscale/imposm3/parser/pbf/process.go:54 +0xba
Makefile:343: recipe for target 'import-osm' failed
make: *** [import-osm] Error 2
```

**Comment by TomPohys** [comment]
Hi @rakzcs, did you try to delete the `germany.osm.pbf` and let quickstart to download `germany` again? Did you do any change in the Openmaptiles project?

**Comment by TomPohys** [comment]
Hi @rakzcs, a possible workaround is `./quickstart.sh europe/germany`, it downloads Germany from OsmFr. Germany has ID in [Geofabrik JSON](https://download.geofabrik.de/index-v1.json), but it won't it download.

**Comment by TomPohys** [comment]
Today's test was OK and `./quickstart.sh germany` runs OK. So, there is no bug in the OpenMapTiles project. Thanks
