### ISSUE TITLE
Set bbox in .env causes Unable to get min/max zoom error

### ISSUE THREAD

**Issue by nabla1** [openmaptiles/openmaptiles#1090]
./quickstart.sh us
and then set the bbox in .env and remove the us.bbox from data.
Re run ./quickstart.sh us

Got error 

Updating generated tile metadata ...
docker-compose run --rm --user=0:0 openmaptiles-tools \
                mbtiles-tools meta-generate "data/tiles.mbtiles" openmaptiles.yaml --auto-minmax --show-ranges
Connecting to PostgreSQL at postgres:5432, db=openmaptiles, user=openmaptiles...
Traceback (most recent call last):
  File "/usr/src/app/mbtiles-tools", line 159, in <module>
    main()
  File "/usr/src/app/mbtiles-tools", line 112, in main
    asyncio.run(Metadata(args['<mbtiles-file>'], args['--show-json'],
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/src/app/openmaptiles/mbtile_tools.py", line 298, in generate
    self._update_metadata(metadata, auto_minmax, reset, self.mbtiles,
  File "/usr/src/app/openmaptiles/mbtile_tools.py", line 343, in _update_metadata
    raise ValueError("Unable to get min/max zoom - tile data is empty")
ValueError: Unable to get min/max zoom - tile data is empty
make: *** [Makefile:407: generate-tiles] Error 1

**Comment by TomPohys** [comment]
Hi @nabla1, if your bbox is out of `us`, then the mbtiles will be empty.
