### ISSUE TITLE
Whitespaces in custom OSM data throws: Error 1

### ISSUE THREAD

**Issue by jvolker** [openmaptiles/openmaptiles#1105]
Eg. `./quickstart.sh "St. Tropez"` for OSM file `St. Tropez.osm.pbf` throws:

```
ID 'St. Tropez' was not found in Geofabrik.
Traceback (most recent call last):
  File "/usr/src/app/download-osm", line 763, in <module>
    main()
  File "/usr/src/app/download-osm", line 759, in main
    exit(asyncio.run(main_async(docopt(__doc__, version=openmaptiles.__version__))))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/src/app/download-osm", line 676, in main_async
    urls, md5, repl_url, bbox = await AreaParamParser(
  File "/usr/src/app/download-osm", line 600, in parse
    res = await site.search(self.area_id, self.is_guessing)
  File "/usr/src/app/download-osm", line 530, in search
    poly = await fetch(self.session, f"https://download.openstreetmap.fr/polygons/{area_id}.poly")
  File "/usr/src/app/download-osm", line 371, in fetch
    raise ValueError(f"Received status={resp.status}")
ValueError: Received status=404
1
make: *** [download] Error 1
```

`./quickstart.sh "St.Tropez"` for OSM file `St.Tropez.osm.pbf` (without the space) works though.

If it's the expected behaviour it would be good to note that in the QUICKSTART.md.

Thanks.

**Comment by TomPohys** [comment]
The space in the name is not a good practice. To figure it out, I think, there must be some workaround for detecting files with `wildcard` (https://github.com/openmaptiles/openmaptiles/blob/master/Makefile#L316)

**Comment by jvolker** [comment]
Thanks for your reply.

> The space in the name is not a good practice.

I know, but it would be quite handy. ;)

By the way, `make generate-bbox-file area="St. Tropez"` works.

**Comment by TomPohys** [comment]
In fact, it is not working correctly :-( There is also a wildcard and it calculates a bbox file every time. If you try e.g. just "Tropez", it will calculate a bbox once, and for the second run, it raises a notice that bbox already exists.
