### ISSUE TITLE
make generate-tiles-pg results in "error: function getmvt does not exist"

### ISSUE THREAD

**Issue by tobltobs** [openmaptiles/openmaptiles#1217]
Following the instructions of the readme I come to the last step of `make generate-tiles-pg`. But this results in the following error. 

```
...
Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432...
Failed to get a tile at [14,9268,3575] from postgres:5432 (in 1ms), aborting tilelive-pgquery initialization:
error: function getmvt(unknown, unknown, unknown) does not exist
/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

error: function getmvt(unknown, unknown, unknown) does not exist
    at Parser.parseErrorMessage (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
...
```

I tried this with the latest and v3.12.2, both with the same result.

**Comment by nyurik** [comment]
`getmvt` is generated by the `build-sql` step. You might have incorrect content in the `build` dir - you may want to clean it first with `make clean`.

**Comment by tobltobs** [comment]
Thank you for your fast reply. The reason was that I did not run `make import-sql`. 

They instructions say that

> Each time you modify layer SQL code run make and make import-sql.

So I thought I do not have to run it at the initial setup as it might get triggered by another task, but it seems that it has to be run in the initial setup also.

**Comment by Falke-Design** [comment]
> They instructions say that
> 
> > Each time you modify layer SQL code run make and make import-sql.
> 
> So I thought I do not have to run it at the initial setup as it might get triggered by another task, but it seems that it has to be run in the initial setup also.

While my first tries I misunderstood it too. For this I created PR #1203
