### ISSUE TITLE
quickstart Error: Invalid minzoom param - an integer zoom value was expected

### ISSUE THREAD

**Issue by BBoldenow** [openmaptiles/openmaptiles#1339]
I'm following the instructions to run the basic quickstart (default of Albania) to ensure that everything is generating and running properly, but it is running into the following error:

/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^
Err: Invalid minzoom param - an integer zoom value was expected
    at checkType (/usr/lib/node_modules/tilelive-pgquery/node_modules/@kartotherian/input-validator/validator.js:104:23)
    at PgQuery.init (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:75:5)
    at /usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:38:28
    at Callbackified (util.js:210:5)
    at new PgQuery (/usr/lib/node_modules/tilelive-pgquery/lib/PgQuery.js:38:38)
    at Object.tilelive.load (/usr/lib/node_modules/@mapbox/tilelive/lib/tilelive.js:97:5)
    at /usr/lib/node_modules/@mapbox/tilelive/lib/tilelive.js:335:18
    at pop (/usr/lib/node_modules/@mapbox/tilelive/node_modules/queue-async/queue.js:24:14)
    at Object.defer (/usr/lib/node_modules/@mapbox/tilelive/node_modules/queue-async/queue.js:55:11)
    at Object.tilelive.copy (/usr/lib/node_modules/@mapbox/tilelive/lib/tilelive.js:333:36)
1
make: *** [generate-tiles-pg] Error 1

Running on Windows w/ Linux WSL 2 (Ubuntu 20.04 LTS)
Docker Engine: 20.10.8
Docker Compose: 1.29.2

I really don't have any additional info since I was just following the quickstart instructions, but let me know if more info is needed.

**Comment by BBoldenow** [comment]
Resolved - this was a pathing issue. I needed to pull the source into the proper WSL2 directory.

**Comment by memarv** [comment]
Hi @BBoldenow 
I have the same issue on Windows WSL 2 (Ubuntu 20.04 LTS). Could you please explain how you dealt with solving this problem?

**Comment by TomPohys** [comment]
Hi, there is also my comment about WLS in https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-817099375
