### ISSUE TITLE
 how to generate mbtille file

### ISSUE THREAD

**Issue by toqeer786** [openmaptiles/openmaptiles#1453]
i want to genrate mbtile file from my osm.pbf file but when i run the command : " make generate-tiles-pg" it gives me an error 

"
Failed to get a tile at [14,9268,3575] from postgres:5432/openmaptiles (in 20ms), aborting tilelive-pgquery initialization:
error: function getmvt(unknown, unknown, unknown) does not exist
/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

error: function getmvt(unknown, unknown, unknown) does not exist
    at Parser.parseErrorMessage (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 226,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '34',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '629',
  routine: 'ParseFuncOrColumn'
}
make: *** [Makefile:461: generate-tiles-pg] Error 1"

 can anyone tell me what i missed here  ,and how can i generate mbtille file ?????
i'm using ubuntu 20

**Comment by TomPohys** [comment]
Hi, do you use this step-by-step? https://github.com/openmaptiles/openmaptiles#workflow-to-generate-tiles

`error: function getmvt(unknown, unknown, unknown) does not exist` it looks like you miss the `make import-sql` step.

**Comment by toqeer786** [comment]
thanks
