### ISSUE TITLE
Regression: "invalid input syntax for type integer" error

### ISSUE THREAD

**Issue by setaou** [openmaptiles/openmaptiles#1583]
When generating the zoom level 14 for the planet (pbf from 230904), it stops at the tile 14/2632/6336 with the following error:

```
root@osm:/data/osm/openmaptiles/data# docker compose run -T --rm --user=$(id -u):$(id -g) openmaptiles-tools tilelive-copy --scheme=list --list=/export/test.txt --timeout=180000 --exit --retry=2 --concurrency=24 'pgquery://?database=openmaptiles&host=postgres&port=5432&username=openmaptiles&password=openmaptiles&funcZXY=getmvt&maxpool=24&minzoom=0&maxzoom=14&serverInfo=&specInfo=' mbtiles:///export/tiles.mbtiles
Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432/openmaptiles...
a tile at [14,9268,3575] from postgres:5432/openmaptiles was generated in 565ms.  The result is 15933 bytes detected as gzipped data. 32648 bytes uncompressed.
Test tile begins with 1a. This byte often corresponds to a valid vector tile.
Error getting 14/2632/6336: error: invalid input syntax for type integer: ""
Error getting 14/2632/6336: error: invalid input syntax for type integer: ""
Error getting 14/2632/6336: error: invalid input syntax for type integer: ""
/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

error: invalid input syntax for type integer: ""
    at Parser.parseErrorMessage (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 183,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL function "display_housenumber" statement 1\n' +
    'SQL function "getmvt" statement 1',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '320',
  routine: 'pg_strtoint32'
}
```

I suspected the recent commit [Convert semi-colon separated house numbers to a range](https://github.com/openmaptiles/openmaptiles/commit/a7a50d84bc7e5117453d6e1c179a8a36f105d73b) to be the cause, and indeed it works if I revert it.

**Comment by TomPohys** [comment]
Thanks for pointing this out. @ZeLonewolf could you please look at it as there could be empty string (`Error getting 14/2632/6336: error: invalid input syntax for type integer: ""`)?

**Comment by molind** [comment]
Something strange happens inside of that CASE.

```
CREATE TABLE test_data (
    housenumber text
);

INSERT INTO test_data VALUES
('123;456'),
('789;'),
(';'),
('abc;def'),
('');

CREATE OR REPLACE FUNCTION display_housenumber(raw_housenumber text)
RETURNS text AS $$
  SELECT
    CASE
      WHEN raw_housenumber !~ ';' THEN 'one'
      WHEN raw_housenumber ~ '[^0-9;]' THEN 'two'
      ELSE 
        SUBSTRING(raw_housenumber FROM 1 FOR 1)
    END;
$$ LANGUAGE SQL IMMUTABLE;

SELECT display_housenumber(housenumber) FROM test_data;
```

It shows that last row result is 'one'. But as soon as we change last ELSE statement to the original:

```
CREATE OR REPLACE FUNCTION display_housenumber(raw_housenumber text)
RETURNS text AS $$
  SELECT CASE
    WHEN raw_housenumber !~ ';' THEN raw_housenumber
    WHEN raw_housenumber ~ '[^0-9;]' THEN display_housenumber_nonnumeric(raw_housenumber)
    ELSE
      (SELECT min(value)::text || '–' || max(value)::text
       FROM unnest(string_to_array(raw_housenumber, ';')::int[]) AS value)
  END
$$ LANGUAGE SQL IMMUTABLE;
```

if fails. Looks like it tries to compute result of that branch even before it's used.

**Comment by phanecak-maptiler** [comment]
I've tested with `planetiler-openmaptiles` (since the "housenumber change" mentioned above was already ported there) and I'm not getting error. What might help here are following "strange values" observed in that tile:

- `115½`
- `201 Dallas St`

**Comment by molind** [comment]
@phanecak-maptiler It works fine with `array_remove`.
