### ISSUE TITLE
make generate-tiles and generate-tiles-pg not working

### ISSUE THREAD

**Issue by andymilga** [openmaptiles/openmaptiles#1596]
Hi
installed openmaptiles via docker according documentation. Made:
import-osm
import-wikidata
import-sql
analyze-db
test-perf-null

trying to generate-tiles-pg - getting:
```
Verifying pgquery data source by retrieving a tile at [14,9268,3575] from postgres:5432/openmaptiles...
a tile at [14,9268,3575] from postgres:5432/openmaptiles was generated in 670ms.  The result is 15931 bytes detected as gzipped data. 32648 bytes uncompressed.
Test tile begins with 1a. This byte often corresponds to a valid vector tile.
[18m 18.4s]   0.0000%      2/357.91m @    0/s | ✓ 1 □ 0 | 2272173d 13h 25m 42.0s leftError getting 1/1/0: error: could not resize shared memory segment "/PostgreSQL.3471938520" to 6311936 bytes: No space left on device
Error getting 1/1/1: error: could not resize shared memory segment "/PostgreSQL.1974424976" to 12615680 bytes: No space left on device
Error getting 1/1/1: error: could not resize shared memory segment "/PostgreSQL.3571807010" to 623872 bytes: No space left on device
Error getting 1/1/0: error: could not resize shared memory segment "/PostgreSQL.3890606430" to 2097152 bytes: No space left on device
```

trying generate-tiles - getting
```
make generate-tiles
Using docker compose V1 (docker-compose)
docker-compose run --rm --user=0:0 openmaptiles-tools bash -c 'style-tools recompose openmaptiles.yaml build/style/style.json \
        style/style-header.json && \
        spritezero build/style/sprite /style/icons && spritezero --retina build/style/sprite@2x /style/icons'
Starting postgres docker compose target using default image (no recreate if exists)
Starting openmaptiles_postgres_1 ... done
Wait for PostgreSQL to start...
docker-compose run --rm --user=0:0 openmaptiles-tools pgwait
WARNING: This Mapnik-based method of tile generation is obsolete. Use generate-tiles-pg instead.
Generating tiles into data/planet.mbtiles (will delete if already exists)...
docker-compose run --rm --user=0:0 generate-vectortiles
Generating tiles into /export/planet.mbtiles for zooms 0..14 inside (-180.0,-85.0511,180.0,85.0511) using 10 concurrent I/O operations
/usr/local/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Postgis Plugin: authentication method 10 not supported
Connection string: 'host=postgres port=5432 dbname=openmaptiles user=openmaptiles connect_timeout=4'

    at /usr/local/lib/node_modules/tilelive-tmsource/index.js:111:18
    at Array.map (<anonymous>)
    at normalize (/usr/local/lib/node_modules/tilelive-tmsource/index.js:100:35)
    at TMSource.init (/usr/local/lib/node_modules/tilelive-tmsource/index.js:194:17)
    at /usr/local/lib/node_modules/tilelive-tmsource/index.js:184:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
make: *** [Makefile:462: generate-tiles] Error 1
```

what im missed in docs?

**Comment by TomPohys** [comment]
Hi, This looks like a problem with docker postgresql. Please try https://github.com/openmaptiles/openmaptiles/blob/6c31841f4674f15e15afde346a060cf7c22e6cdd/docker-compose.yml#L16

**Comment by TomPohys** [comment]
Hi @andymilga, any progress here? Thanks

**Comment by TomPohys** [comment]
Closing now, but please do not hesitate to reopen.
