### ISSUE TITLE
 Error: Postgis Plugin

### ISSUE THREAD

**Issue by jaskiratr** [openmaptiles/openmaptiles#165]
I receive the following error after running `docker-compose run generate-vectortiles`
```
docker-compose run generate-vectortiles
WARNING: The MIN_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The MAX_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The BBOX variable is not set. Defaulting to a blank string.
/usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Postgis Plugin: ERROR:  function layer_water_name(geometry, integer) does not exist
LINE 1: ... FROM (SELECT geometry, name, name_en, class FROM layer_wate...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
in executeQuery Full sql was: 'SELECT * FROM (SELECT geometry, name, name_en, class FROM layer_water_name(ST_SetSRID('BOX3D(-3.402823466385289e+38 -3.402823466385289e+38,3.402823466385289e+38 3.402823466385289e+38)'::box3d, 900913), z(3.40282e+38))) AS t LIMIT 0'

    at Error (native)
    at /usr/local/lib/node_modules/tilelive-tmsource/index.js:111:18
    at Array.map (native)
    at normalize (/usr/local/lib/node_modules/tilelive-tmsource/index.js:100:35)
    at /usr/local/lib/node_modules/tilelive-tmsource/index.js:185:19
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
I'm running docker in windows 10 - Pro
Any clues as in what might be causing this?

Thanks!

**Comment by jaskiratr** [comment]
Apologies for the noise.
Fixed it by doing a fresh install of all containers/images. 
Closing the issue.

**Comment by masoud2vg** [comment]
I've reinstalled the images but it gives the same error again
