### ISSUE TITLE
mapbox-studio javascript crashes at launch 

### ISSUE THREAD

**Issue by bryanhuntesl** [openmaptiles/openmaptiles#464]
`SyntaxError: Use of const in strict mode.`

```
mapbox-studio_1                 | 
mapbox-studio_1                 | /usr/src/app/node_modules/mapbox-upload/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
mapbox-studio_1                 | const Hoek = require('hoek');
mapbox-studio_1                 | ^^^^^
mapbox-studio_1                 | SyntaxError: Use of const in strict mode.
mapbox-studio_1                 |     at Module._compile (module.js:439:25)
mapbox-studio_1                 |     at Object.Module._extensions..js (module.js:474:10)
mapbox-studio_1                 |     at Module.load (module.js:356:32)
mapbox-studio_1                 |     at Function.Module._load (module.js:312:12)
mapbox-studio_1                 |     at Module.require (module.js:364:17)
mapbox-studio_1                 |     at require (module.js:380:17)
mapbox-studio_1                 |     at Object.<anonymous> (/usr/src/app/node_modules/mapbox-upload/node_modules/request/node_modules/hawk/lib/index.js:5:33)
mapbox-studio_1                 |     at Module._compile (module.js:456:26)
mapbox-studio_1                 |     at Object.Module._extensions..js (module.js:474:10)
mapbox-studio_1                 |     at Module.load (module.js:356:32)
mapbox-studio_1                 | 
mapbox-studio_1                 | npm ERR! Linux 4.9.87-linuxkit-aufs
mapbox-studio_1                 | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
mapbox-studio_1                 | npm ERR! node v0.10.48
mapbox-studio_1                 | npm ERR! npm  v2.15.1
mapbox-studio_1                 | npm ERR! code ELIFECYCLE
mapbox-studio_1                 | npm ERR! mapbox-studio@0.3.8 start: `./index.js`
mapbox-studio_1                 | npm ERR! Exit status 8
mapbox-studio_1                 | npm ERR! 
mapbox-studio_1                 | npm ERR! Failed at the mapbox-studio@0.3.8 start script './index.js'.
mapbox-studio_1                 | npm ERR! This is most likely a problem with the mapbox-studio package,
mapbox-studio_1                 | npm ERR! not with npm itself.
mapbox-studio_1                 | npm ERR! Tell the author that this fails on your system:
mapbox-studio_1                 | npm ERR!     ./index.js
mapbox-studio_1                 | npm ERR! You can get information on how to open an issue for this project with:
mapbox-studio_1                 | npm ERR!     npm bugs mapbox-studio
mapbox-studio_1                 | npm ERR! Or if that isn't available, you can get their info via:
mapbox-studio_1                 | npm ERR! 
mapbox-studio_1                 | npm ERR!     npm owner ls mapbox-studio
mapbox-studio_1                 | npm ERR! There is likely additional logging output above.
mapbox-studio_1                 | 
mapbox-studio_1                 | npm ERR! Please include the following file with any support request:
mapbox-studio_1                 | npm ERR!     /usr/src/app/npm-debug.log
openmaptiles_mapbox-studio_1 exited with code 1
```

**Comment by klokan** [comment]
Sorry, but it does not sound as an issue of this openmaptiles repository...
