### ISSUE TITLE
generate-vectortiles failed for bad indentation

### ISSUE THREAD

**Issue by masoud2vg** [openmaptiles/openmaptiles#672]
this is my error --> 

/usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^
YAMLException: bad indentation of a mapping entry at line 9, column 39:
     ... th open(filename, 'r') as stream:
                                         ^
    at generateError (/usr/local/lib/node_modules/tilelive-tmsource/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/usr/local/lib/node_modules/tilelive-tmsource/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/usr/local/lib/node_modules/tilelive-tmsource/node_modules/js-yaml/lib/js-yaml/loader.js:1107:7)
    at composeNode (/usr/local/lib/node_modules/tilelive-tmsource/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/usr/local/lib/node_modules/tilelive-tmsource/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/usr/local/lib/node_modules/tilelive-tmsource/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/usr/local/lib/node_modules/tilelive-tmsource/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at /usr/local/lib/node_modules/tilelive-tmsource/index.js:182:24
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

**Comment by klokan** [comment]
Have you modified the yaml configs?

How to reproduce your problem.
I don't see any error against the config form master now / quickstart.
