### ISSUE TITLE
make generate-tiles error

### ISSUE THREAD

**Issue by yetzt** [openmaptiles/openmaptiles#924]
After days of waiting, this happened:

![screenshot](https://imgur.com/HrZCd3U.png)

```
/usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Copy operation timed out
    at Timeout.<anonymous> (/usr/local/lib/node_modules/tilelive/lib/tilelive.js:390:22)
    at Timeout.wrapper (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by nyurik** [comment]
This just means your postgres server (most likely) timed out on a query. You may need to increase the timeout, or get a bigger machine for this.

**Comment by yetzt** [comment]
bigger than an EPYC 7502P with 128gb of ram? what do you recommend?
